Repository noahsb/portfolio, pull requests merged in 2020-10, with the labels that each got.

#11 Add avatar and dependency
  gatsby-config.js
  package.json
  src/@lekoarts/gatsby-theme-minimal-blog/texts/ProfileCard.jsx
  src/@lekoarts/gatsby-theme-minimal-blog/texts/hero.mdx
  yarn.lock
Labels: enhancement

#12 Update README.md
  README.md
Labels: documentation, hacktoberfest-2020

#13 Add lambda blog post
  content/posts/aws-lambda-starter/add-trigger.jpg
  content/posts/aws-lambda-starter/create-function.jpg
  content/posts/aws-lambda-starter/edit-settings.jpg
  content/posts/aws-lambda-starter/environment-variables.jpg
  content/posts/aws-lambda-starter/index.mdx
  content/posts/aws-lambda-starter/python-lambda.jpg
  content/posts/aws-lambda-starter/upload-function.jpg
  content/posts/curses-and-counter-courses/index.mdx
  content/posts/fantastic-beasts-and-where-to-find-them/SpotifyPlayer.js
  content/posts/fantastic-beasts-and-where-to-find-them/index.mdx
  content/posts/harry-potter-and-the-half-blood-prince/index.mdx
  content/posts/introduction-to-defence-against-the-dark-arts/defence-against-the-dark-arts.jpg
  content/posts/introduction-to-defence-against-the-dark-arts/index.mdx
  content/posts/introduction-to-defence-against-the-dark-arts/potions.jpg
Labels: enhancement

#14 Fix links
  content/posts/aws-lambda-starter/index.mdx
  gatsby-config.js
  src/@lekoarts/gatsby-theme-minimal-blog/texts/bottom.mdx
Labels: bug

#16 Fix GA Tracking
  content/pages/about/index.mdx
  package.json
  static/robots.txt
  yarn.lock
Labels: bug

#17 Fix profile image size
  src/@lekoarts/gatsby-theme-minimal-blog/texts/ProfileCard.jsx
  static/profile-img.png
Labels: bug

#18 Add comment box
  content/posts/CommentBox.jsx
  content/posts/aws-lambda-starter/index.mdx
  package.json
  yarn.lock
Labels: enhancement
